version: 2.1
jobs:
  test:
    docker:
      - image: node:14
    steps:
      - checkout
      - run: yarn
      - run: yarn test
      - run: yarn audit
      - run: npx yarn-audit-fix
workflows:
  Testing:
    jobs:
      - test
