version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test:
    docker:
      - image: node:14
    steps:
      - checkout
      - node/install-packages:
        pkg-manager: yarn   
      - run: jest
